### ISSUE TITLE
loading templete in every file ?

### ISSUE THREAD

**Issue by mali1991** [scoumbourdis/codeigniter-simplicity#3]
Do i have to load the template in every controller .... or there  is a way that default template is loaded automatically

**Comment by ozturkmtn** [comment]
Hi there,
i add one function to MY_output page. Then i called each controller this function.
for front side and panel side used different sections. 
with this function i can send different data to template also.

	function load_template($type = NULL){
	    $CI =& get_instance ();
	    $CI->load->library('menu');
	    
	    if ($type == 'panel'){
	        $section = 'sections/panel';
	    }
	    if ($type == 'front'){
	        $section = 'sections/front';
	        $data["menu"] = $CI->menu->front_menu();
	    }
	    $this->set_template('panel');
	    $CI->load->section('head', $section.'/head');
	    $CI->load->section('nav', $section.'/nav',$data??"");
	    $CI->load->section('footer', $section.'/footer');
	}
i can send dynamic menu items to template now.
